### ISSUE TITLE
Inlcuding "starter kit" in the build.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt-distribution#26]
When packaging the `.tgz` and `.zip` archives, we need to include the new [starter kit](https://github.com/bolt/starter-kit) extension in the build process.. 

@GawainLynch Could you help out with this one?

**Comment by GawainLynch** [comment]
Of course, see my comment in #25 … Let's use next week to have a good pooke at this stuff :smile:

**Comment by bobdenotter** [comment]
Sure thing! 👍

**Comment by bobdenotter** [comment]
I've tried to make this work on my own, but couldn't figure out what the intended way to do this is. :-(

**Comment by GawainLynch** [comment]
Let's do the immediate follow-up up on Slack. :smile:

**Comment by GawainLynch** [comment]
Done in d12e7362e11d85d463633423607af24ef5276ac1
