### ISSUE TITLE
Built files are missing the web assets. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt-distribution#27]
After installing the latest built dev setup, with this: 

```
curl -O https://bolt.cm/distribution/bolt-3.3.x-dev.tar.gz
tar -xzf bolt-3.3.x-dev.tar.gz --strip-components=1
php app/nut init
```

I get a screen like this: 

![screen shot 2017-01-30 at 20 10 42](https://cloud.githubusercontent.com/assets/1833361/22437388/2e36dc58-e728-11e6-80ae-7c0ea6ccd10e.png)

Looks like the web assets are missing from the distro.

```
$ ls -als public/bolt-public/view/css
total 0
0 drwxr-xr-x  2 bob2  staff   68 Jan 29 11:43 .
0 drwxr-xr-x  6 bob2  staff  204 Jan 29 11:43 ..
```

Same for `bolt_public/view/fonts/`, `bolt_public/view/img/` and `bolt_public/view/js/`.

When building using package.sh, they're alread not included. 

If i manually run `php app/nut setup:sync`, I get this: 

```
Directory synchronisation encountered problems:
RecursiveDirectoryIterator::__construct(../test/vendor/bolt/boltapp/view/css): failed to open dir: No such file or directory
RecursiveDirectoryIterator::__construct(../test/vendor/bolt/boltapp/view/fonts): failed to open dir: No such file or directory
RecursiveDirectoryIterator::__construct(../test/vendor/bolt/boltapp/view/img): failed to open dir: No such file or directory
RecursiveDirectoryIterator::__construct(../test/vendor/bolt/boltapp/view/js): failed to open dir: No such file or directory
```

Seems like a missing slash in the middle of `boltapp`.

**Comment by GawainLynch** [comment]
> ../test/vendor/bolt/boltapp/view/js

Looks like Guns n' Roses without Saul Hudson … Slash is missing.

**Comment by bobdenotter** [comment]
Was fixed..
