### ISSUE TITLE
"Flat" version needs a tweak in index.php.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt-distribution#29]
When packaging the 'flat' version of the distro, we need to change the path in the require in index.php:

```
$app = require __DIR__ . '/../vendor/bolt/bolt/app/web.php';
```

to: 

``` 
$app = require __DIR__ . '/vendor/bolt/bolt/app/web.php';
```

Should be an easy fix, so i'll self-assign.

**Comment by GawainLynch** [comment]
:koala: :koala: :koala: :koala: :koala:
